spring:
  application:
    name: Vitt

  datasource:
    url: jdbc:mysql://localhost:3306/vitt_db_qa?createDatabaseIfNotExist=true
 
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    data: import.sql

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    osiride.vitt-be: DEBUG
    org.springframework.web: ERROR
    