spring:
  application:
    name: Vitt

  datasource:
    url: jdbc:mysql://localhost:3306/vitt_db?createDatabaseIfNotExist=true
 
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    initialize: true
    data: import.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
