spring:
  application:
    name: Vitt

  datasource:
    url: jdbc:h2:mem:vitt
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

logging:
  level:
    root: INFO
    osiride.vitt-be: DEBUG
    org.springframework.web: ERROR
